CON?=.

download:
	norare --norarepo=. --repos=$(CON) download Abdaoui-2017-EmoLex
	norare --norarepo=. --repos=$(CON) download Alonso-2011-OralFrequency
	norare --norarepo=. --repos=$(CON) download Alonso-2015-AoA
	norare --norarepo=. --repos=$(CON) download Alonso-2016-AoA
	norare --norarepo=. --repos=$(CON) download Bond-2013-OMW
	norare --norarepo=. --repos=$(CON) download Briesemeister-2011-DiscreteEmotions
	norare --norarepo=. --repos=$(CON) download Brysbaert-2009-Frequency
	norare --norarepo=. --repos=$(CON) download Brysbaert-2011-Frequency
	norare --norarepo=. --repos=$(CON) download Brysbaert-2014-Concreteness
	norare --norarepo=. --repos=$(CON) download Brysbaert-2019-Prevalence
	norare --norarepo=. --repos=$(CON) download Cai-2010-Frequency
	norare --norarepo=. --repos=$(CON) download Chedid-2019-Familiarity
	norare --norarepo=. --repos=$(CON) download Clark-2004-ImageryFamiliarity
	norare --norarepo=. --repos=$(CON) download Cortese-2008-AoA
	norare --norarepo=. --repos=$(CON) download Crepaldi-2015-Frequency
	norare --norarepo=. --repos=$(CON) download Cuetos-2011-Frequency
	norare --norarepo=. --repos=$(CON) download Desrochers-2009-SubjFrequency
	norare --norarepo=. --repos=$(CON) download Engelthaler-2018-Humor
	norare --norarepo=. --repos=$(CON) download Ferrand-2010-LexicalDecision
	norare --norarepo=. --repos=$(CON) download Ferre-2017-DiscreteEmotions
	norare --norarepo=. --repos=$(CON) download Gilhooly-1980-Ratings
	norare --norarepo=. --repos=$(CON) download GonzalezNosti-2014-LexicalDecision
	norare --norarepo=. --repos=$(CON) download Imbir-2016-Ratings
	norare --norarepo=. --repos=$(CON) download Juhasz-2013-SER
	norare --norarepo=. --repos=$(CON) download Kapucu-2018-EmotionRatings
	norare --norarepo=. --repos=$(CON) download Keuleers-2010-Frequency
	norare --norarepo=. --repos=$(CON) download Keuleers-2012-LexicalDecision
	norare --norarepo=. --repos=$(CON) download Keuleers-2015-Prevalence
	norare --norarepo=. --repos=$(CON) download Kiss-1973-EAT
	norare --norarepo=. --repos=$(CON) download Kuperman-2012-AoA
	norare --norarepo=. --repos=$(CON) download Lynott-2020-Sensorimotor
	norare --norarepo=. --repos=$(CON) download Mandera-2015-Frequency
	norare --norarepo=. --repos=$(CON) download Matisoff-2015-STEDT
	norare --norarepo=. --repos=$(CON) download Medler-2005-Perceptual
	norare --norarepo=. --repos=$(CON) download Mohammad-2018-AffectiveRatings
	norare --norarepo=. --repos=$(CON) download Mohammad-2018-EmotionIntensity
	norare --norarepo=. --repos=$(CON) download Moors-2013-Ratings
	norare --norarepo=. --repos=$(CON) download Riegel-2015-AffectiveRatings
	norare --norarepo=. --repos=$(CON) download Scott-2019-Ratings
	norare --norarepo=. --repos=$(CON) download Speed-2021-Sensorimotor
	norare --norarepo=. --repos=$(CON) download StadthagenGonzalez-2017-ValenceArousal
	norare --norarepo=. --repos=$(CON) download StadthagenGonzalez-2018-DiscreteEmotions
	norare --norarepo=. --repos=$(CON) download Starostin-2000-Sense
	norare --norarepo=. --repos=$(CON) download Tsang-2018-LexicalDecision
	norare --norarepo=. --repos=$(CON) download VanHeuven-2014-Frequency
	norare --norarepo=. --repos=$(CON) download Warriner-2013-AffectiveRatings
	norare --norarepo=. --repos=$(CON) download Wierzba-2015-DiscreteEmotions
	norare --norarepo=. --repos=$(CON) download Wu-2020-CoreVocabulary
