CON?=.

download:
	norare --norarepo=. --repos=$(CON) download Abdaoui-2017-EmoLex
	norare --norarepo=. --repos=$(CON) download Alonso-2011-OralFrequency
	norare --norarepo=. --repos=$(CON) download Alonso-2015-AoA
	norare --norarepo=. --repos=$(CON) download Alonso-2016-AoA
	norare --norarepo=. --repos=$(CON) download Bond-2013-OMW
	norare --norarepo=. --repos=$(CON) download Briesemeister-2011-DiscreteEmotions
	norare --norarepo=. --repos=$(CON) download Brysbaert-2009-Frequency
	norare --norarepo=. --repos=$(CON) download Brysbaert-2011-Frequency
	norare --norarepo=. --repos=$(CON) download Brysbaert-2014-Concreteness
	norare --norarepo=. --repos=$(CON) download Brysbaert-2019-Prevalence
	norare --norarepo=. --repos=$(CON) download Cai-2010-Frequency
	norare --norarepo=. --repos=$(CON) download Chedid-2019-Familiarity
	norare --norarepo=. --repos=$(CON) download Clark-2004-ImageryFamiliarity
	norare --norarepo=. --repos=$(CON) download Cortese-2008-AoA
	norare --norarepo=. --repos=$(CON) download Crepaldi-2015-Frequency
	norare --norarepo=. --repos=$(CON) download Cuetos-2011-Frequency
	norare --norarepo=. --repos=$(CON) download Desrochers-2009-SubjFrequency
	norare --norarepo=. --repos=$(CON) download Engelthaler-2018-Humor
	norare --norarepo=. --repos=$(CON) download Ferrand-2010-LexicalDecision
	norare --norarepo=. --repos=$(CON) download Ferre-2017-DiscreteEmotions
	norare --norarepo=. --repos=$(CON) download Juhasz-2013-SER
	norare --norarepo=. --repos=$(CON) download Kapucu-2018-EmotionRatings
	norare --norarepo=. --repos=$(CON) download Keuleers-2010-Frequency
	norare --norarepo=. --repos=$(CON) download Keuleers-2012-LexicalDecision
	norare --norarepo=. --repos=$(CON) download Keuleers-2015-Prevalence
	norare --norarepo=. --repos=$(CON) download Kiss-1973-EAT
	norare --norarepo=. --repos=$(CON) download Kuperman-2012-AoA
	norare --norarepo=. --repos=$(CON) download Lynott-2020-Sensorimotor
	norare --norarepo=. --repos=$(CON) download Mandera-2015-Frequency
	norare --norarepo=. --repos=$(CON) download Matisoff-2015-STEDT
	norare --norarepo=. --repos=$(CON) download Moors-2013-Ratings
	norare --norarepo=. --repos=$(CON) download Riegel-2015-AffectiveRatings
	norare --norarepo=. --repos=$(CON) download Scott-2019-Ratings
	norare --norarepo=. --repos=$(CON) download Speed-2021-Sensorimotor
	norare --norarepo=. --repos=$(CON) download StadthagenGonzalez-2017-ValenceArousal
	norare --norarepo=. --repos=$(CON) download StadthagenGonzalez-2018-DiscreteEmotions
	norare --norarepo=. --repos=$(CON) download Tsang-2018-LexicalDecision
	norare --norarepo=. --repos=$(CON) download VanHeuven-2014-Frequency
	norare --norarepo=. --repos=$(CON) download Warriner-2013-AffectiveRatings
	norare --norarepo=. --repos=$(CON) download Wierzba-2015-DiscreteEmotions
	norare --norarepo=. --repos=$(CON) download Wu-2020-CoreVocabulary

map:
	norare --norarepo=. --repos=$(CON) map Abdaoui-2017-EmoLex
	norare --norarepo=. --repos=$(CON) map Alonso-2011-OralFrequency
	norare --norarepo=. --repos=$(CON) map Alonso-2015-AoA
	norare --norarepo=. --repos=$(CON) map Alonso-2016-AoA
	norare --norarepo=. --repos=$(CON) map Bond-2013-OMW
	norare --norarepo=. --repos=$(CON) map Briesemeister-2011-DiscreteEmotions
	norare --norarepo=. --repos=$(CON) map Brysbaert-2009-Frequency
	norare --norarepo=. --repos=$(CON) map Brysbaert-2011-Frequency
	norare --norarepo=. --repos=$(CON) map Brysbaert-2014-Concreteness
	norare --norarepo=. --repos=$(CON) map Brysbaert-2019-Prevalence
	norare --norarepo=. --repos=$(CON) map Cai-2010-Frequency
	norare --norarepo=. --repos=$(CON) map Chedid-2019-Familiarity
	norare --norarepo=. --repos=$(CON) map Clark-2004-ImageryFamiliarity
	norare --norarepo=. --repos=$(CON) map Cortese-2008-AoA
	norare --norarepo=. --repos=$(CON) map Crepaldi-2015-Frequency
	norare --norarepo=. --repos=$(CON) map Cuetos-2011-Frequency
	norare --norarepo=. --repos=$(CON) map Desrochers-2009-SubjFrequency
	norare --norarepo=. --repos=$(CON) map Engelthaler-2018-Humor
	norare --norarepo=. --repos=$(CON) map Ferrand-2010-LexicalDecision
	norare --norarepo=. --repos=$(CON) map Ferre-2017-DiscreteEmotions
	norare --norarepo=. --repos=$(CON) map Juhasz-2013-SER
	norare --norarepo=. --repos=$(CON) map Kapucu-2018-EmotionRatings
	norare --norarepo=. --repos=$(CON) map Keuleers-2010-Frequency
	norare --norarepo=. --repos=$(CON) map Keuleers-2012-LexicalDecision
	norare --norarepo=. --repos=$(CON) map Keuleers-2015-Prevalence
	norare --norarepo=. --repos=$(CON) map Kiss-1973-EAT
	norare --norarepo=. --repos=$(CON) map Kuperman-2012-AoA
	norare --norarepo=. --repos=$(CON) map Lynott-2020-Sensorimotor
	norare --norarepo=. --repos=$(CON) map Mandera-2015-Frequency
	norare --norarepo=. --repos=$(CON) map Matisoff-2015-STEDT
	norare --norarepo=. --repos=$(CON) map Moors-2013-Ratings
	norare --norarepo=. --repos=$(CON) map Riegel-2015-AffectiveRatings
	norare --norarepo=. --repos=$(CON) map Scott-2019-Ratings
	norare --norarepo=. --repos=$(CON) map Speed-2021-Sensorimotor
	norare --norarepo=. --repos=$(CON) map StadthagenGonzalez-2017-ValenceArousal
	norare --norarepo=. --repos=$(CON) map StadthagenGonzalez-2018-DiscreteEmotions
	norare --norarepo=. --repos=$(CON) map Tsang-2018-LexicalDecision
	norare --norarepo=. --repos=$(CON) map VanHeuven-2014-Frequency
	norare --norarepo=. --repos=$(CON) map Warriner-2013-AffectiveRatings
	norare --norarepo=. --repos=$(CON) map Wierzba-2015-DiscreteEmotions
	norare --norarepo=. --repos=$(CON) map Wu-2020-CoreVocabulary
